name: Build image

on:
  push:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      should_push:
        type: boolean
        description: Push image to registries
        required: true

jobs:
  build:
    env:
      SHOULD_PUSH: false
    runs-on: ubuntu-latest

    steps:
      - name: Set SHOULD_PUSH to true
        if: "contains(github.ref, 'main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.should_push)"
        run: echo "SHOULD_PUSH=true" >> $GITHUB_ENV
          
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v4.0.0
        with:
          push: ${{ env.SHOULD_PUSH }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
